name: CI/CD Pipeline

on:
  push:
    branches: [ main ]


jobs:

  continuous-integration:
    runs-on: ubuntu-latest
  
- name: AWS Lambda Deploy
      uses: actions/checkout@v2
      with:
            function_name: Helloworld
            zip_file: Helloworld.zip
            architecture: x86_64
            
- name: Configure AWS credentials from secrets
      uses: 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_Region }}
        runtime: Node.js 14.x
        
